# Generated by Django 5.0.1 on 2024-03-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='nid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
