# Generated by Django 5.0.1 on 2024-03-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Train', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='train',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Train/media/uploads/'),
        ),
        migrations.AddField(
            model_name='train',
            name='station',
            field=models.ManyToManyField(to='Train.station'),
        ),
    ]
