# Generated by Django 5.0.1 on 2024-03-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Train', '0002_station_train_image_train_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
